algoritmo "Primeiro Programa"

var

numero, numero2, numero3, numero4 : inteiro
resultado : real

inicio


'( Feito em dupla com Rian

escreval("Digite um número inteiro: ")
leia(numero)
escreval("Digite outro número inteiro: ")
leia(numero2)
escreval("Digite outro número inteiro: ")
leia(numero3)
escreval("Digite outro número inteiro: ")
leia(numero4)
resultado <- numero + numero2
escreval("Resultado da soma: ", resultado)
resultado <- numero3 - numero4
escreval("Resultado da subtração: ", resultado)
resultado <- numero * numero2
escreval("Resultado da multiplicação: ", resultado)
resultado <- numero / numero2
escreval("Resultado da divisão: ", resultado)

fimalgoritmo