algoritmo "Primeiro Programa"
 
//Receba 3 números do teclado e para cada um imprima true se o número for par e false se o número for ímpar

var


numero1, numero2, numero3: inteiro

inicio

Escreval("informe o numero inteiro: ")
leia(numero1)
Escreval("informe o numero inteiro: ")
leia(numero2)
Escreval("informe o numero inteiro: ")
leia(numero3)
se numero1 % 2 = 0 entao
escreval("True")
senao
escreval("False")
fimse
se numero2 % 2 = 0 entao
escreval("True")
senao
escreval("False")
fimse
se numero3 % 2 = 0 entao
escreval("True")
senao
escreval("False")
fimse

fimalgoritmo